name: Workflow Testing
on:
  push
#   schedule:
#     - cron: '1-59/6 * * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Running Perfectly............................"
      - name: Second Step
        run: ls
      - name: Third Step
        run: touch sample.txt
      - name: Fourth Step
        run: ls
      - name: 5 Step
        run: pwd
