name: Workflow Testing
on:
  schedule:
    - cron: '15 5 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Running Perfectly.................................."
