name: Workflow Testing
on:
  schedule:
    - cron: '1-59/6 * * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Running Perfectly.................................."
      - name: Second Step
        run: python --version
      - name: Third Step
        run: conda env list
      - name: Fourth Step
        run: ls
      - name: 5 Step
        run: pwd
      - name: 6 Step
        run: conda create --name new_env
      - name: 7 Step
        run: touch sample_file_to_see_data_persistancy.txt
      - name: 8 Step
        run: conda install -c conda-forge mlflow
      - name: 9 Step
        run: mlflow --version
      - name: 10 Step
        run: ls
