name: Workflow Testing
on:
#   push:
#     branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: dir visulization
        run: pwd
      - name: Clonning
        uses: actions/checkout@v3
        with:
          ref: main
      - name: dir visulization
        run: ls -ll
#       - name: dir visulization
#         run: cd 
      - name: Fourth Step
        run: pwd
      - name: curren dir
        run: python hello.py
