name: Workflow Testing
on:
  push
#   schedule:
#     - cron: '1-59/6 * * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Clonning
        uses: actions/checkout@v3
#         with:
#           path: main
      - name: dir visulization
        run: ls
      - name: Fourth Step
        run: cd test
      - name: dir visulaization
        run: ls
      - name: curren dir
        run: pwd
