name: Workflow Testing
on:
  schedule:
    - cron: '1-59/6 * * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Running Perfectly.................................."
      - name: Second Step
        run: python --version
      - name: Third Step
        run: conda env list
      - name: Fourth Step
        run: ls
      - name: 5 Step
        run: pwd
      - name: 10 Step
        run: docker version
